name: Build and Push Docker Images

on:
  # [workflow_dispatch]
    push:
        branches: [ "maintung" ]
    pull_request:
        branches: [ "maintung" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push r-service
      uses: docker/build-push-action@v5
      with:
        context: ./src/r_service
        push: true
        tags: codemaivanngu/mhcat-r-service:${{ env.IMAGE_TAG }}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./src/backend
        push: true
        tags: codemaivanngu/mhcat-backend:${{ env.IMAGE_TAG }}

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: codemaivanngu/mhcat-frontend:${{ env.IMAGE_TAG }}
